# -*- coding: utf-8 -*-
"""검색 동의어 — 개수보다 먼저 고쳐야 하는 것.

2026-09-03 감사: 사이트에 손으로 그려 넣은 아이콘 129종 중 110여 종이
**이미 우리 세트에 있는데 못 찾아서** 다시 그린 것이었다.
「나가기」로 door 가 안 나오고, 「통계」로 chart-bar 가 안 나온다.
그래서 사람이 실제로 치는 말을 아이콘에 붙여 둔다.

원칙: 그림을 늘리기 전에 이름을 늘린다.
"""
SYN = {
 # 드나들기 · 계정
 "door": "나가기 로그아웃 들어가기 로그인 출입 exit logout login signout",
 "person": "사용자 유저 계정 프로필 회원 user account profile",
 "avatar": "사용자 유저 계정 프로필 내정보 user account profile",
 "person-add": "회원가입 초대 사용자추가 invite signup",
 "user-lock": "권한 접근제한 계정잠금 permission",
 "id-card": "신분증 명함 사원증 프로필카드 badge",
 "fingerprint": "생체인증 지문 로그인 biometric",
 # 목록 · 정렬 · 보기
 "sort": "정렬 순서 오름차순 내림차순 order sort",
 "swap-vertical": "정렬 위아래 바꾸기 순서변경 reorder",
 "list-bullet": "목록 리스트 항목 list",
 "list-check": "체크리스트 할일 todo checklist",
 "dots-grid": "격자 그리드 바둑판 앱목록 grid apps",
 "table": "표 테이블 시트 grid table",
 "filter": "필터 거르기 조건 추리기 filter",
 "menu": "메뉴 햄버거 목록 menu",
 "expand": "펼치기 확대 크게 expand",
 "collapse": "접기 축소 작게 collapse",
 # 데이터 · 차트
 "chart-bar": "통계 막대그래프 차트 데이터 분석 statistics bar",
 "chart-line": "추이 꺾은선 그래프 차트 트렌드 trend line",
 "chart-pie": "비중 원그래프 파이 점유율 share pie",
 "chart-area": "면적그래프 누적 추이 area",
 "chart-candle": "캔들 봉차트 주가 candlestick",
 "dashboard": "대시보드 현황판 요약 overview",
 "trend-up": "상승 증가 오름 올랐다 상향 up rise",
 "trend-down": "하락 감소 내림 떨어졌다 하향 down fall",
 "gauge": "게이지 계기판 수준 measure",
 "pulse": "실시간 심박 활동 live activity",
 # 시간
 "history": "기록 히스토리 최근 지난 이력 되돌리기 history recent",
 "clock": "시간 시계 시각 time clock",
 "calendar": "달력 일정 날짜 스케줄 calendar date",
 "timer": "타이머 남은시간 카운트 timer",
 "stopwatch": "스톱워치 경과 측정 elapsed",
 "hourglass": "대기 처리중 모래시계 waiting pending",
 # 알림 · 상태
 "bell": "알림 소식 공지 푸시 notification alert",
 "progress": "로딩 진행 처리중 스피너 loading spinner",
 "sync": "새로고침 동기화 갱신 재시도 refresh sync reload",
 "refresh": "새로고침 갱신 다시 reload refresh",
 "success": "성공 완료 정상 done ok",
 "error": "실패 오류 에러 문제 fail error",
 "warning": "경고 주의 확인필요 warning caution",
 "info": "안내 정보 설명 도움말 info help",
 # 돈 · 거래
 "card": "카드 결제 신용카드 payment card",
 "wallet": "지갑 잔액 자산 balance wallet",
 "won": "원화 금액 가격 돈 krw won money",
 "coin": "코인 잔돈 금액 money coin",
 "receipt": "영수증 내역 명세 거래내역 receipt",
 "bank": "은행 계좌 금융 bank account",
 "price-tag": "가격 할인 태그 price tag",
 "portfolio": "포트폴리오 보유 자산 holdings",
 # 소통
 "chat": "말풍선 대화 채팅 댓글 메시지 chat comment message",
 "chat-lines": "대화 채팅 상담 conversation",
 "mail": "메일 편지 이메일 쪽지 mail email",
 "send": "보내기 전송 발송 send submit",
 "reply": "답장 회신 reply",
 "share": "공유 내보내기 링크복사 share",
 "megaphone": "공지 알림 홍보 announce",
 # 소리 · 미디어
 "mic": "마이크 녹음 음성입력 voice record mic",
 "voice-wave": "음성 목소리 파형 발음 voice speech",
 "volume-high": "소리 음량 스피커 volume sound",
 "volume-off": "음소거 무음 소리끔 mute",
 "play": "재생 시작 play start",
 "pause": "일시정지 멈춤 pause",
 "stop": "정지 중단 stop",
 "headphones": "헤드폰 듣기 이어폰 listen",
 # 파일 · 문서
 "doc": "문서 파일 페이지 document file",
 "doc-add": "새문서 문서추가 새파일 new document",
 "folder": "폴더 디렉터리 folder",
 "download": "다운로드 내려받기 저장 download save",
 "upload": "업로드 올리기 첨부 upload attach",
 "copy": "복사 클립보드 copy duplicate",
 "paste": "붙여넣기 paste",
 "printer": "인쇄 출력 print",
 "archive": "보관 아카이브 저장소 archive",
 # 편집
 "edit": "편집 수정 연필 쓰기 edit pencil write",
 "trash": "삭제 지우기 휴지통 버리기 delete remove trash",
 "close": "닫기 취소 지우기 엑스 close cancel",
 "check": "확인 완료 체크 동의 check done",
 "plus": "추가 새로만들기 더하기 add new plus",
 "minus": "빼기 제거 축소 minus remove",
 "more": "더보기 기타 옵션 메뉴 more options",
 "search": "검색 찾기 조회 search find",
 "undo": "되돌리기 취소 이전 undo",
 "redo": "다시실행 앞으로 redo",
 "eye": "보기 표시 미리보기 view show preview",
 "eye-off": "숨기기 비표시 가리기 hide",
 # 설정 · 시스템
 "gear": "설정 환경설정 옵션 톱니 settings preferences",
 "settings": "설정 환경설정 옵션 조절 settings sliders",
 "slider": "조절 슬라이더 값조정 adjust slider",
 "toggle-on": "켬 활성 스위치 on enable",
 "toggle-off": "끔 비활성 스위치 off disable",
 "power": "전원 종료 시작 power",
 "lock": "잠금 보안 비밀 lock secure",
 "unlock": "잠금해제 열기 unlock",
 "shield-check": "보안 안전 검증 verified secure",
 "key": "열쇠 비밀번호 인증 password key",
 # 이동 · 방향
 "chevron-right": "다음 오른쪽 이동 펼치기 next right",
 "chevron-left": "이전 왼쪽 뒤로 back left",
 "arrow-up-right": "바로가기 외부링크 새창 external open",
 "link": "링크 연결 주소 url link",
 "location": "위치 현재위치 장소 location place",
 "navigation": "길찾기 내비 방향 navigate",
 "globe": "언어 국가 웹 인터넷 세계 language web global",
 # 기기 · 화면
 "mobile": "휴대폰 모바일 스마트폰 phone mobile",
 "desktop": "데스크톱 컴퓨터 화면 pc desktop",
 "laptop": "노트북 랩탑 laptop",
 "tv": "티브이 화면 모니터 display tv",
 "wifi": "와이파이 무선 연결 wifi network",
 "signal-bars": "신호 세기 수신 signal",
 "battery": "배터리 충전 잔량 battery",
 # 기타 자주 찾는 것
 "star": "즐겨찾기 별 평점 favorite star rating",
 "bookmark": "북마크 저장 담기 bookmark save",
 "heart": "좋아요 관심 하트 like heart",
 "flag": "신고 표시 깃발 flag report",
 "pin": "고정 핀 상단고정 pin",
 "sparkle": "AI 자동 추천 반짝 magic ai",
 "magic-wand": "AI 자동 마법 generate ai",
 "bulb": "아이디어 팁 제안 idea tip",
 "target": "목표 타깃 정확도 target goal",
 "flame": "인기 급상승 핫 hot trending",
 "gift": "선물 혜택 이벤트 gift benefit",
 "cart": "장바구니 주문 구매 cart order",
 "bag": "쇼핑 가방 구매 shop bag",
 "box": "상자 패키지 배송 package box",
 "truck": "배송 운송 택배 delivery shipping",
 "home": "홈 처음 메인 home main",
 "layers": "레이어 층 겹 stack layers",
 "code": "코드 개발 소스 code dev",
 "terminal": "터미널 명령 콘솔 cli terminal",
 "database": "데이터베이스 저장소 db database",
 "server": "서버 호스트 server",
 "qrcode": "큐알 코드 스캔 qr",
 "scan": "스캔 인식 촬영 scan",
 "camera": "카메라 사진촬영 camera",
 "photo": "사진 이미지 그림 image photo",
 "film": "영상 동영상 비디오 video film",
 "book-open": "가이드 문서 읽기 매뉴얼 guide docs",
 "trophy": "우승 랭킹 성취 trophy rank",
 "medal": "메달 순위 성과 medal",
 # 2026-09-03 신규 19종
 "logout": "나가기 로그아웃 종료 exit signout",
 "login": "들어가기 로그인 입장 signin",
 "translate": "번역 언어 다국어 통역 translate",
 "chat-question": "문의 질문 도움말 ask",
 "chat-add": "새대화 문의하기 new chat",
 "person-voice": "말하기 음성인식 발화 speaking",
 "spinner": "로딩 처리중 대기 loading",
 "plus-circle": "추가 새로만들기 add",
 "bookmark-check": "저장됨 담김 saved",
 "hexagon-check": "검증 인증 확인됨 verified",
 "dot": "점 표시 bullet",
 "grid-2x2": "격자 타일 4분할 grid",
 "face": "표정 감정 이모지 반응 mood",
 "chess-pawn": "체스 폰 pawn",
 "chess-rook": "체스 룩 성 rook",
 "chess-bishop": "체스 비숍 bishop",
 "chess-knight": "체스 나이트 knight",
 "chess-queen": "체스 퀸 queen",
 "chess-king": "체스 킹 왕 king",
 # 대시보드 결손 보충
 "chart-donut": "도넛 비중 구성비 donut",
 "chart-scatter": "산점도 분포 상관 scatter",
 "chart-stacked": "누적막대 스택 stacked",
 "chart-funnel": "퍼널 전환 단계 funnel",
 "chart-heatmap": "히트맵 밀도 heatmap",
 "chart-radar": "레이더 방사형 radar",
 "sparkline": "스파크라인 미니차트 sparkline",
 "no-data": "데이터없음 빈상태 결과없음 empty",
 "forecast": "예측 전망 추정 forecast",
 "outlier": "이상치 특이값 anomaly",
 "axis": "축 눈금 좌표 axis",
 "legend": "범례 계열 legend",
 "orderbook": "호가 잔량 주문창 orderbook",
 "volume-bar": "거래량 체결량 volume",
 "dividend": "배당 분배 dividend",
 "watchlist": "관심종목 관심목록 watchlist",
 "pnl": "손익 수익률 평가손익 profit loss",
 "stop-loss": "손절 스톱로스 방어선 stoploss",
 "exchange": "환전 교환 통화변환 exchange",
 "radio-on": "선택됨 라디오 radio",
 "radio-off": "선택안됨 라디오 radio",
 "checkbox-on": "체크됨 선택 checkbox",
 "checkbox-off": "체크안됨 빈체크 checkbox",
 "dropdown": "드롭다운 선택목록 select",
 "stepper": "수량조절 증감 stepper",
}
